[project]
name = "fomu-blink-verilog"
version = "0.1.0"
description = "Dependencies for building and uploading to FPGA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyrtl>=0.11.2",
    "yowasp-nextpnr-ice40>=0.8.0.0.post621",
    "yowasp-yosys>=0.53.0.0.post912",
]
